name: Update Domain IPs

on:
  schedule:
    - cron: '0 0 * * *'  # 每天UTC时间00:00运行
  workflow_dispatch:     # 允许手动触发

jobs:
  update-ips:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install dig
      run: sudo apt-get update && sudo apt-get install -y dnsutils
      
    - name: Resolve domain and save IPs (one per line)
      run: |
        # 替换为你想要解析的域名
        DOMAIN="cfip.xxxxxxxx.tk"
        
        # 使用dig解析域名并获取所有IP，每行一个
        dig +short "$DOMAIN" | grep -E '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$' | sort -u > chaip.txt
        
        # 统计IP数量
        COUNT=$(wc -l < chaip.txt | tr -d ' ')
        echo "Found $COUNT unique IPs for $DOMAIN"
        
    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add chaip.txt
        git diff --quiet && git diff --staged --quiet || git commit -m "Update IP addresses [skip ci]"
        git push
