name: Update Domain IPs

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  update-ips:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write  # 必须添加这个权限
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        persist-credentials: true
        fetch-depth: 0
      
    - name: Install dig
      run: sudo apt-get update && sudo apt-get install -y dnsutils
      
    - name: Resolve domain and save IPs
      run: |
        DOMAIN="cfip.xxxxxxxx.tk"
        dig +short "$DOMAIN" | grep -E '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$' | sort -u > chaip.txt
        
    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add chaip.txt
        git diff --cached --quiet || git commit -m "Update IP addresses [skip ci]"
        git push
